-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 18:35:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bankdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bankdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankdb` DEFAULT CHARACTER SET utf8 ;
USE `bankdb` ;

-- -----------------------------------------------------
-- Table `bankdb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`customer` (
  `idCustomer` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `streetAddress` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`card` (
  `idCard` VARCHAR(20) NOT NULL,
  `cardPin` VARCHAR(255) NOT NULL,
  `cardValid` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`account` (
  `idAccount` VARCHAR(18) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL,
  `creditLimit` DECIMAL(10,2) NOT NULL,
  `accountOwner` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `accountOwner_idx` (`accountOwner` ASC) VISIBLE,
  CONSTRAINT `accountOwner`
    FOREIGN KEY (`accountOwner`)
    REFERENCES `bankdb`.`customer` (`idCustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`customeraccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`customeraccount` (
  `idCustomer` VARCHAR(45) NOT NULL,
  `idAccount` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`idCustomer`, `idAccount`),
  INDEX `tili_id_idx` (`idAccount` ASC) VISIBLE,
  CONSTRAINT `customerIdCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `bankdb`.`customer` (`idCustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `accountIdAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `bankdb`.`account` (`idAccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `idAccount` VARCHAR(18) NOT NULL,
  `idCard` VARCHAR(20) NULL DEFAULT NULL,
  `dateAndTime` DATETIME NOT NULL,
  `transactionType` VARCHAR(45) NOT NULL,
  `transactionAmount` DECIMAL(10,2) NOT NULL,
  `participantAccount` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `idAccount_idx` (`idAccount` ASC) VISIBLE,
  CONSTRAINT `transactionIdAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `bankdb`.`account` (`idAccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`cardaccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`cardaccount` (
  `idCard` VARCHAR(20) NOT NULL,
  `idAccount` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`idCard`, `idAccount`),
  INDEX `idAccount_idx` (`idAccount` ASC) VISIBLE,
  CONSTRAINT `cardIdCard`
    FOREIGN KEY (`idCard`)
    REFERENCES `bankdb`.`card` (`idCard`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cardIdAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `bankdb`.`account` (`idAccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
